services:

  api:
    build: .
    container_name: axiomeet-api

    command:
      [
        "uvicorn",
        "src.api.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]

    ports:
      - "8000:8000"

  ui:
    build: .

    environment:
      APP_ENV: docker
      
    container_name: axiomeet-ui

    command:
      [
        "streamlit",
        "run",
        "app/streamlit/app.py",
        "--server.address=0.0.0.0"
      ]

    ports:
      - "8501:8501"

    depends_on:
      - api